### ISSUE TITLE
nord-iterm2 slightly dimmer than nord-alacritty

### ISSUE THREAD

**Issue by bdeak4** [arcticicestudio/nord-iterm2#10]
Hey, I've noticed that Nord colors in iterm2 are slightly dimmer than same in Alacritty terminal.
Left - iterm2
Right - Alacritty
<img width="494" alt="Screen Shot 2019-11-01 at 16 07 17" src="https://user-images.githubusercontent.com/32748145/68035129-4bad9480-fcc3-11e9-8383-082bc546f6e6.png">
iterm2 settings:
<img width="581" alt="Screen Shot 2019-11-01 at 16 09 41" src="https://user-images.githubusercontent.com/32748145/68035229-831c4100-fcc3-11e9-93f0-0dbd2e434dc4.png">
Alacritty settings:
```
colors:
   primary:
     background: '0x2E3440'
     foreground: '0xD8DEE9'
   cursor:
     text: '0x2E3440'
     cursor: '0xD8DEE9'
   normal:
     black: '0x3B4252'
     red: '0xBF616A'
     green: '0xA3BE8C'
     yellow: '0xEBCB8B'
     blue: '0x81A1C1'
     magenta: '0xB48EAD'
     cyan: '0x88C0D0'
     white: '0xE5E9F0'
   bright:
     black: '0x4C566A'
     red: '0xBF616A'
     green: '0xA3BE8C'
     yellow: '0xEBCB8B'
     blue: '0x81A1C1'
     magenta: '0xB48EAD'
     cyan: '0x8FBCBB'
     white: '0xECEFF4'
```

I am not sure if this is bug with one of those terminal emulators or is one theme outdated?
